import { NextRequest, NextResponse } from "next/server";
import { AIProjectClient } from "@azure/ai-projects";
import { DefaultAzureCredential } from "@azure/identity";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * GET /api/submittal/download/[fileId]
 *
 * Downloads a file generated by the Foundry Agent.
 */
export async function GET(
    req: NextRequest,
    { params }: { params: { fileId: string } }
) {
    const fileId = params.fileId;

    try {
        const endpoint = process.env.AZURE_AI_FOUNDRY_ENDPOINT;

        if (!endpoint) {
            throw new Error("Missing Azure AI Foundry endpoint");
        }

        const credential = new DefaultAzureCredential();
        const client = AIProjectClient.fromEndpoint(endpoint, credential);

        // Get file metadata
        const file = await client.agents.files.get(fileId);

        // Get file content
        const contentResponse = await client.agents.files.getContent(fileId);

        const filename = file.filename || `submittal-${fileId}.pdf`;

        // contentResponse from getFileContent is typically the body stream or buffer
        // If it returns a specialized object, we might need to process it.
        // Assuming it matches generic BodyInit compatible type.

        return new NextResponse(contentResponse as BodyInit, {
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": `attachment; filename="${filename}"`,
                "Cache-Control": "no-cache",
            },
        });

    } catch (error) {
        console.error("❌ Download Error:", error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : "Internal server error" },
            { status: 500 }
        );
    }
}
