const DeployAnalyzer = require('../services/deployAnalyzer');
const fs = require('fs');

async function main() {
  const [fromCommit, toCommit] = process.argv.slice(2);

  if (!fromCommit) {
    console.error('Usage: node analyze-deploy.js <from-commit> [to-commit]');
    process.exit(1);
  }

  const analyzer = new DeployAnalyzer();
  const report = await analyzer.generateReport(fromCommit, toCommit);

  console.log('\n' + '='.repeat(80));
  console.log('DEPLOYMENT ANALYSIS REPORT');
  console.log('='.repeat(80));
  console.log(`\nCommit Range: ${report.commitRange}`);
  console.log(`Generated: ${report.generatedAt}\n`);
  console.log(`📊 Statistics:`);
  console.log(`   Added: ${report.stats.added} files`);
  console.log(`   Modified: ${report.stats.modified} files`);
  console.log(`   Deleted: ${report.stats.deleted} files`);
  console.log(`\n🤖 AI Analysis:\n`);
  console.log(report.aiAnalysis.summary);

  const markdown = `# 🚀 Deployment Analysis

**Commit Range:** ${report.commitRange}  
**Generated:** ${report.generatedAt}

## 📊 Changes Summary

- **Added:** ${report.stats.added} files
- **Modified:** ${report.stats.modified} files
- **Deleted:** ${report.stats.deleted} files

## 🤖 AI Analysis

${report.aiAnalysis.summary}

---
*Generated by GreenChainz Deploy Analyzer*
`;

  fs.writeFileSync('deploy-report.md', markdown);
  console.log('\n✅ Report saved to deploy-report.md');

  await analyzer.postToSlack(report);
}

main().catch(error => {
  console.error('Error:', error);
  process.exit(1);
});
