/**
 * PDF Export API
 * 
 * POST /api/export/pdf
 * Generates PDF reports for carbon analytics, RFQs, etc.
 */
import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '../../../../lib/mongodb';

interface PdfExportRequest {
    type: 'carbon_report' | 'rfq_summary' | 'product_comparison' | 'project_report';
    data: Record<string, any>;
    format?: 'a4' | 'letter';
}

/**
 * Generate HTML template for carbon report PDF
 */
function generateCarbonReportHtml(data: {
    companyName: string;
    reportPeriod: string;
    totalCo2e: number;
    projects: Array<{
        name: string;
        co2e: number;
        materials: number;
    }>;
    categories: Array<{
        name: string;
        co2e: number;
        percentage: number;
    }>;
    generatedAt: string;
}): string {
    const projectsHtml = data.projects.map(p => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${p.name}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">${p.materials}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">${(p.co2e / 1000).toFixed(2)} t</td>
    </tr>
  `).join('');

    const categoriesHtml = data.categories.map(c => `
    <div style="margin-bottom: 12px;">
      <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
        <span>${c.name}</span>
        <span>${(c.co2e / 1000).toFixed(2)} t CO2e (${c.percentage}%)</span>
      </div>
      <div style="height: 8px; background-color: #e5e7eb; border-radius: 4px; overflow: hidden;">
        <div style="height: 100%; width: ${c.percentage}%; background-color: #10b981; border-radius: 4px;"></div>
      </div>
    </div>
  `).join('');

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Carbon Report - ${data.reportPeriod}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1f2937; line-height: 1.5; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #10b981; }
    .logo { font-size: 24px; font-weight: bold; color: #10b981; }
    .report-info { text-align: right; color: #6b7280; font-size: 14px; }
    .main-metric { background: linear-gradient(135deg, #065f46, #047857); color: white; border-radius: 12px; padding: 32px; text-align: center; margin-bottom: 32px; }
    .main-metric h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; opacity: 0.8; margin-bottom: 8px; }
    .main-metric .value { font-size: 48px; font-weight: bold; }
    .main-metric .unit { font-size: 18px; opacity: 0.9; }
    .section { margin-bottom: 32px; }
    .section h3 { font-size: 18px; color: #1f2937; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #e5e7eb; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; padding: 12px; background-color: #f3f4f6; font-weight: 600; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">🌱 GreenChainz</div>
    <div class="report-info">
      <div><strong>${data.companyName}</strong></div>
      <div>Carbon Report: ${data.reportPeriod}</div>
      <div>Generated: ${data.generatedAt}</div>
    </div>
  </div>

  <div class="main-metric">
    <h2>Total Embodied Carbon</h2>
    <div class="value">${(data.totalCo2e / 1000).toFixed(1)}</div>
    <div class="unit">tonnes CO2e</div>
  </div>

  <div class="section">
    <h3>Projects Summary</h3>
    <table>
      <thead>
        <tr>
          <th>Project Name</th>
          <th style="text-align: right;">Materials</th>
          <th style="text-align: right;">Carbon Footprint</th>
        </tr>
      </thead>
      <tbody>
        ${projectsHtml}
      </tbody>
    </table>
  </div>

  <div class="section">
    <h3>Carbon by Category</h3>
    ${categoriesHtml}
  </div>

  <div class="footer">
    <p>This report was generated by GreenChainz - Sustainable Building Materials Marketplace</p>
    <p>Data based on EPD-verified carbon factors and Autodesk carbon calculations</p>
  </div>
</body>
</html>
`;
}

/**
 * Generate HTML template for RFQ summary PDF
 */
function generateRfqSummaryHtml(data: {
    rfqNumber: string;
    productName: string;
    quantity: number;
    unit: string;
    buyer: { company: string; name: string; email: string };
    project: string;
    deliveryLocation: string;
    deliveryDate: string;
    specifications?: string;
    quotes: Array<{
        supplier: string;
        unitPrice: number;
        leadTime: number;
        carbonFootprint?: number;
    }>;
    generatedAt: string;
}): string {
    const quotesHtml = data.quotes.map((q, i) => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${i + 1}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${q.supplier}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">$${q.unitPrice.toLocaleString()}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">$${(q.unitPrice * data.quantity).toLocaleString()}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">${q.leadTime} days</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">${q.carbonFootprint ? (q.carbonFootprint / 1000).toFixed(2) + ' t' : 'N/A'}</td>
    </tr>
  `).join('');

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>RFQ Summary - ${data.rfqNumber}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1f2937; line-height: 1.5; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #10b981; }
    .logo { font-size: 24px; font-weight: bold; color: #10b981; }
    .rfq-number { background-color: #f3f4f6; padding: 8px 16px; border-radius: 8px; font-weight: 600; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 32px; }
    .info-box { background-color: #f9fafb; border-radius: 8px; padding: 20px; }
    .info-box h4 { font-size: 12px; text-transform: uppercase; color: #6b7280; margin-bottom: 8px; }
    .info-box p { font-size: 16px; font-weight: 500; }
    .product-highlight { background: linear-gradient(135deg, #065f46, #047857); color: white; border-radius: 12px; padding: 24px; margin-bottom: 32px; }
    .product-highlight h2 { font-size: 24px; margin-bottom: 8px; }
    .section { margin-bottom: 32px; }
    .section h3 { font-size: 18px; color: #1f2937; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #e5e7eb; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { text-align: left; padding: 12px; background-color: #f3f4f6; font-weight: 600; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">🌱 GreenChainz</div>
    <div class="rfq-number">${data.rfqNumber}</div>
  </div>

  <div class="product-highlight">
    <h2>${data.productName}</h2>
    <p>${data.quantity.toLocaleString()} ${data.unit}</p>
  </div>

  <div class="info-grid">
    <div class="info-box">
      <h4>Buyer</h4>
      <p>${data.buyer.company}</p>
      <p style="font-weight: normal; font-size: 14px; color: #6b7280;">${data.buyer.name} • ${data.buyer.email}</p>
    </div>
    <div class="info-box">
      <h4>Project</h4>
      <p>${data.project}</p>
    </div>
    <div class="info-box">
      <h4>Delivery Location</h4>
      <p>${data.deliveryLocation}</p>
    </div>
    <div class="info-box">
      <h4>Delivery Date</h4>
      <p>${data.deliveryDate}</p>
    </div>
  </div>

  ${data.specifications ? `
  <div class="section">
    <h3>Specifications</h3>
    <p style="white-space: pre-wrap; background-color: #f9fafb; padding: 16px; border-radius: 8px;">${data.specifications}</p>
  </div>
  ` : ''}

  <div class="section">
    <h3>Quotes Comparison</h3>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Supplier</th>
          <th style="text-align: right;">Unit Price</th>
          <th style="text-align: right;">Total</th>
          <th style="text-align: right;">Lead Time</th>
          <th style="text-align: right;">Carbon</th>
        </tr>
      </thead>
      <tbody>
        ${quotesHtml}
      </tbody>
    </table>
  </div>

  <div class="footer">
    <p>Generated: ${data.generatedAt}</p>
    <p>GreenChainz - Sustainable Building Materials Marketplace</p>
  </div>
</body>
</html>
`;
}

/**
 * Generate HTML template for product comparison PDF
 */
function generateProductComparisonHtml(data: {
    products: Array<{
        name: string;
        supplier: string;
        price: number;
        unit: string;
        carbonFootprint: number;
        certifications: string[];
        leadTime: number;
    }>;
    generatedAt: string;
}): string {
    const productsHtml = data.products.map(p => `
    <div style="flex: 1; background-color: #f9fafb; border-radius: 12px; padding: 20px; min-width: 200px;">
      <h4 style="font-size: 16px; margin-bottom: 4px;">${p.name}</h4>
      <p style="color: #6b7280; font-size: 14px; margin-bottom: 16px;">${p.supplier}</p>
      
      <div style="margin-bottom: 16px;">
        <div style="font-size: 12px; color: #6b7280;">Price</div>
        <div style="font-size: 20px; font-weight: 600; color: #10b981;">$${p.price.toLocaleString()}/${p.unit}</div>
      </div>
      
      <div style="margin-bottom: 16px;">
        <div style="font-size: 12px; color: #6b7280;">Carbon Footprint</div>
        <div style="font-size: 18px; font-weight: 600;">${(p.carbonFootprint).toFixed(2)} kg CO2e/${p.unit}</div>
      </div>
      
      <div style="margin-bottom: 16px;">
        <div style="font-size: 12px; color: #6b7280;">Lead Time</div>
        <div style="font-size: 16px;">${p.leadTime} days</div>
      </div>
      
      <div>
        <div style="font-size: 12px; color: #6b7280; margin-bottom: 8px;">Certifications</div>
        <div style="display: flex; flex-wrap: wrap; gap: 4px;">
          ${p.certifications.map(c => `<span style="background-color: #d1fae5; color: #065f46; padding: 2px 8px; border-radius: 4px; font-size: 12px;">${c}</span>`).join('')}
        </div>
      </div>
    </div>
  `).join('');

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Product Comparison</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1f2937; line-height: 1.5; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #10b981; }
    .logo { font-size: 24px; font-weight: bold; color: #10b981; }
    .comparison-grid { display: flex; gap: 20px; margin-bottom: 32px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">🌱 GreenChainz</div>
    <div style="color: #6b7280;">Product Comparison</div>
  </div>

  <h2 style="margin-bottom: 24px;">Side-by-Side Comparison</h2>

  <div class="comparison-grid">
    ${productsHtml}
  </div>

  <div class="footer">
    <p>Generated: ${data.generatedAt}</p>
    <p>GreenChainz - Sustainable Building Materials Marketplace</p>
  </div>
</body>
</html>
`;
}

export async function POST(request: NextRequest) {
    try {
        const body = await request.json() as PdfExportRequest;

        if (!body.type || !body.data) {
            return NextResponse.json(
                { error: 'Missing type or data' },
                { status: 400 }
            );
        }

        let html: string;
        const generatedAt = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });

        switch (body.type) {
            case 'carbon_report':
                html = generateCarbonReportHtml({ ...body.data, generatedAt });
                break;

            case 'rfq_summary':
                html = generateRfqSummaryHtml({ ...body.data, generatedAt });
                break;

            case 'product_comparison':
                html = generateProductComparisonHtml({ ...body.data, generatedAt });
                break;

            case 'project_report':
                html = generateCarbonReportHtml({ ...body.data, generatedAt }); // Reuse carbon report template
                break;

            default:
                return NextResponse.json(
                    { error: 'Invalid report type' },
                    { status: 400 }
                );
        }

        // Log the export
        try {
            const { db } = await connectToDatabase();
            await db.collection('export_logs').insertOne({
                type: body.type,
                format: 'pdf',
                createdAt: new Date(),
            });
        } catch (logError) {
            console.warn('Failed to log export:', logError);
        }

        // Return HTML that can be converted to PDF client-side
        // In production, you'd use a service like Puppeteer, wkhtmltopdf, or a PDF API
        return NextResponse.json({
            success: true,
            html,
            // For client-side PDF generation
            printInstructions: 'Use window.print() or a library like html2pdf.js to convert to PDF',
        });

    } catch (error) {
        console.error('PDF export error:', error);
        return NextResponse.json(
            { error: 'Internal server error' },
            { status: 500 }
        );
    }
}
