import { type Material } from "../components/catalog/MaterialCard";
import { type CertificationType } from "../components/catalog/CertificationBadge";

export interface MaterialDetail extends Material {
  description: string;
  specifications: Record<string, string>;
  environmentalData: {
    gwp?: number;
    embodiedCarbon?: number;
    recyclableContent?: number;
    recycledContent?: number;
    voc?: number;
    waterUsage?: number;
  };
  certificationDetails: Array<{
    name: string;
    issuedDate: string;
    expiryDate?: string;
    documentUrl?: string;
  }>;
  suppliers: Array<{
    id: string;
    name: string;
    location: string;
    verified: boolean;
    rating?: number;
  }>;
  priceRangeMin?: number;
  priceRangeMax?: number;
  createdAt: string;
  updatedAt: string;
}

export const CATEGORIES = [
  {
    id: "flooring",
    name: "Flooring",
    count: 24,
    subcategories: [
      { id: "hardwood", name: "Hardwood", count: 8 },
      { id: "cork", name: "Cork", count: 4 },
      { id: "tile", name: "Tile", count: 7 },
      { id: "carpet", name: "Carpet", count: 5 },
    ],
  },
  {
    id: "structural",
    name: "Structural",
    count: 18,
    subcategories: [
      { id: "steel", name: "Steel", count: 6 },
      { id: "timber", name: "Timber", count: 8 },
      { id: "concrete", name: "Concrete", count: 4 },
    ],
  },
  {
    id: "insulation",
    name: "Insulation",
    count: 15,
    subcategories: [
      { id: "natural-fiber", name: "Natural Fiber", count: 5 },
      { id: "foam", name: "Foam", count: 6 },
      { id: "mineral-wool", name: "Mineral Wool", count: 4 },
    ],
  },
  { id: "windows", name: "Windows", count: 12 },
  { id: "cladding", name: "Cladding", count: 10 },
  { id: "roofing", name: "Roofing", count: 14 },
  { id: "masonry", name: "Masonry", count: 9 },
  { id: "wall-finishes", name: "Wall Finishes", count: 16 },
  { id: "coatings", name: "Coatings", count: 11 },
  { id: "hardscape", name: "Hardscape", count: 8 },
];

export const CERTIFICATIONS: { id: CertificationType; name: string; count: number }[] =
  [
    { id: "leed", name: "LEED Certified", count: 156 },
    { id: "fsc", name: "FSC Certified", count: 89 },
    { id: "epd", name: "EPD Verified", count: 124 },
    { id: "breeam", name: "BREEAM", count: 67 },
    { id: "greenguard", name: "GREENGUARD Gold", count: 45 },
    { id: "cradle-to-cradle", name: "Cradle to Cradle", count: 32 },
    { id: "energy-star", name: "ENERGY STAR", count: 28 },
    { id: "declare", name: "Declare Label", count: 41 },
  ];

export const MANUFACTURERS = [
  { id: "ecotimber", name: "EcoTimber Inc.", count: 12 },
  { id: "greencore", name: "GreenCore Steel", count: 8 },
  { id: "biofiber", name: "BioFiber Solutions", count: 6 },
  { id: "clearvue", name: "ClearVue Glass", count: 9 },
  { id: "terracotta", name: "TerraCotta Systems", count: 5 },
  { id: "solarshade", name: "SolarShade Tech", count: 4 },
  { id: "hempbuild", name: "HempBuild Co.", count: 3 },
  { id: "recycleroof", name: "RecycleRoof Industries", count: 7 },
  { id: "aquaguard", name: "AquaGuard Outdoor", count: 5 },
  { id: "ecowall", name: "EcoWall Designs", count: 8 },
  { id: "purecoat", name: "PureCoat Labs", count: 6 },
  { id: "corktech", name: "CorkTech International", count: 4 },
];

export const MOCK_MATERIALS: MaterialDetail[] = [
  {
    id: "mat-001",
    name: "EcoTimber Premium Hardwood Flooring",
    category: "Flooring",
    subcategory: "Hardwood",
    manufacturer: "EcoTimber Inc.",
    image: "/placeholder-material.png",
    sustainabilityScore: 92,
    certifications: ["fsc", "leed", "epd"],
    leedPoints: 8,
    carbonFootprint: 12.4,
    recycledContent: 35,
    verifiedSuppliers: 8,
    shadowSuppliers: 12,
    featured: true,
    description: 'Premium sustainably sourced hardwood flooring with FSC certification. Our EcoTimber Premium line combines traditional craftsmanship with modern sustainability standards, offering exceptional durability while minimizing environmental impact.',
    specifications: {
      'Thickness': '3/4 inch (19mm)',
      'Width': '5 inch (127mm)',
      'Length': 'Random lengths 12"-84"',
      'Species': 'White Oak',
      'Finish': 'UV-cured polyurethane',
      'Janka Hardness': '1360 lbf',
      'Installation': 'Nail, Staple, or Glue Down',
      'Warranty': '50 Year Residential',
    },
    environmentalData: {
      gwp: 12.4,
      embodiedCarbon: 8.2,
      recyclableContent: 100,
      recycledContent: 35,
      voc: 0.02,
      waterUsage: 45,
    },
    certificationDetails: [
      { name: 'FSC Certified', issuedDate: '2023-01-15', documentUrl: '#' },
      { name: 'LEED Credit Compliant', issuedDate: '2023-03-20', documentUrl: '#' },
      { name: 'EPD Verified', issuedDate: '2023-06-01', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's1', name: 'GreenBuild Supply', location: 'Portland, OR', verified: true, rating: 4.8 },
      { id: 's2', name: 'EcoMaterials Direct', location: 'Seattle, WA', verified: true, rating: 4.6 },
      { id: 's3', name: 'Sustainable Floors Inc', location: 'San Francisco, CA', verified: false, rating: 4.2 },
    ],
    priceRange: "$8 - $15 / sq ft",
    priceRangeMin: 8,
    priceRangeMax: 15,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: "mat-002",
    name: "GreenCore Recycled Steel Beams",
    category: "Structural",
    subcategory: "Steel",
    manufacturer: "GreenCore Steel",
    image: "/placeholder-material.png",
    sustainabilityScore: 88,
    certifications: ["epd", "leed"],
    leedPoints: 6,
    carbonFootprint: 45.2,
    recycledContent: 95,
    verifiedSuppliers: 5,
    shadowSuppliers: 8,
    description: "High-strength steel beams manufactured with 95% recycled content. Reduces embodied carbon significantly compared to virgin steel production.",
    specifications: {
      "Grade": "A992",
      "Yield Strength": "50 ksi",
      "Tensile Strength": "65 ksi",
      "Finish": "Mill Finish or Primed",
      "Sizes": "W8-W24 available",
    },
    environmentalData: {
      gwp: 45.2,
      embodiedCarbon: 450,
      recyclableContent: 100,
      recycledContent: 95,
      waterUsage: 120,
    },
    certificationDetails: [
      { name: 'EPD Verified', issuedDate: '2023-02-10', documentUrl: '#' },
      { name: 'LEED Credit Compliant', issuedDate: '2023-04-15', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's4', name: 'SteelWorks Inc', location: 'Pittsburgh, PA', verified: true, rating: 4.7 },
      { id: 's5', name: 'BuildMetal Co', location: 'Gary, IN', verified: true, rating: 4.5 },
    ],
    priceRange: "$1200 - $1500 / ton",
    priceRangeMin: 1200,
    priceRangeMax: 1500,
    createdAt: '2023-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: "mat-003",
    name: "BioFiber Insulation Panels",
    category: "Insulation",
    subcategory: "Natural Fiber",
    manufacturer: "BioFiber Solutions",
    image: "/placeholder-material.png",
    sustainabilityScore: 95,
    certifications: ["greenguard", "declare", "epd"],
    leedPoints: 10,
    carbonFootprint: 3.2,
    recycledContent: 80,
    verifiedSuppliers: 3,
    shadowSuppliers: 5,
    featured: true,
    description: "Bio-based insulation panels made from hemp and wood fibers. Excellent thermal performance and humidity regulation.",
    specifications: {
      "R-Value": "R-13 per 3.5 inches",
      "Density": "2.5 lbs/ft³",
      "Fire Rating": "Class A",
      "Vapor Permeability": "High",
    },
    environmentalData: {
      gwp: 3.2,
      embodiedCarbon: 1.5,
      recyclableContent: 100,
      recycledContent: 80,
      voc: 0,
    },
    certificationDetails: [
      { name: 'GREENGUARD Gold', issuedDate: '2023-03-01', documentUrl: '#' },
      { name: 'Declare Label', issuedDate: '2023-03-05', documentUrl: '#' },
      { name: 'EPD Verified', issuedDate: '2023-03-10', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's6', name: 'Natural Insulations', location: 'Denver, CO', verified: true, rating: 4.9 },
    ],
    priceRange: "$1.20 - $1.50 / sq ft",
    priceRangeMin: 1.2,
    priceRangeMax: 1.5,
    createdAt: '2023-02-01T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: "mat-004",
    name: "ClearVue Low-E Triple Glazing",
    category: "Windows",
    subcategory: "Glazing",
    manufacturer: "ClearVue Glass",
    image: "/placeholder-material.png",
    sustainabilityScore: 78,
    certifications: ["energy-star", "epd"],
    leedPoints: 5,
    carbonFootprint: 28.5,
    recycledContent: 20,
    verifiedSuppliers: 6,
    shadowSuppliers: 4,
    description: "High-performance triple pane glazing units with double Low-E coating. Maximizes energy efficiency in cold climates.",
    specifications: {
      "U-Factor": "0.18",
      "SHGC": "0.25",
      "VT": "0.65",
      "Spacer": "Warm Edge",
    },
    environmentalData: {
      gwp: 28.5,
      embodiedCarbon: 150,
      recyclableContent: 100,
      recycledContent: 20,
    },
    certificationDetails: [
      { name: 'ENERGY STAR', issuedDate: '2023-05-12', documentUrl: '#' },
      { name: 'EPD Verified', issuedDate: '2023-06-20', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's7', name: 'GlassPro', location: 'Chicago, IL', verified: true, rating: 4.4 },
    ],
    priceRange: "$40 - $60 / sq ft",
    priceRangeMin: 40,
    priceRangeMax: 60,
    createdAt: '2023-03-15T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: "mat-005",
    name: "TerraCotta Rain Screen Panels",
    category: "Cladding",
    subcategory: "Terracotta",
    manufacturer: "TerraCotta Systems",
    image: "/placeholder-material.png",
    sustainabilityScore: 72,
    certifications: ["leed", "breeam"],
    leedPoints: 4,
    carbonFootprint: 18.9,
    recycledContent: 15,
    verifiedSuppliers: 4,
    shadowSuppliers: 7,
    description: "Natural fired clay rain screen facade system. Durable, color-fast, and maintenance-free.",
    specifications: {
      "Thickness": "30mm",
      "Weight": "12 lbs/sq ft",
      "Frost Resistance": "Passed",
      "Water Absorption": "< 3%",
    },
    environmentalData: {
      gwp: 18.9,
      embodiedCarbon: 22,
      recyclableContent: 100,
      recycledContent: 15,
    },
    certificationDetails: [
      { name: 'LEED Credit Compliant', issuedDate: '2022-11-10', documentUrl: '#' },
      { name: 'BREEAM Certified', issuedDate: '2023-01-20', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's8', name: 'Facade Supply', location: 'New York, NY', verified: true, rating: 4.6 },
    ],
    priceRange: "$25 - $35 / sq ft",
    priceRangeMin: 25,
    priceRangeMax: 35,
    createdAt: '2023-04-10T00:00:00Z',
    updatedAt: '2024-04-10T00:00:00Z',
  },
  {
    id: "mat-006",
    name: "SolarShade Dynamic Glass",
    category: "Windows",
    subcategory: "Smart Glass",
    manufacturer: "SolarShade Tech",
    image: "/placeholder-material.png",
    sustainabilityScore: 85,
    certifications: ["energy-star", "leed", "epd"],
    leedPoints: 7,
    carbonFootprint: 32.1,
    recycledContent: 25,
    verifiedSuppliers: 2,
    shadowSuppliers: 3,
    description: "Electrochromic smart glass that tints on demand to control glare and heat gain.",
    specifications: {
      "U-Factor": "0.29 (Center of Glass)",
      "SHGC": "0.41 - 0.09 (Variable)",
      "VT": "60% - 1% (Variable)",
      "Switching Speed": "3-5 minutes",
    },
    environmentalData: {
      gwp: 32.1,
      embodiedCarbon: 180,
      recyclableContent: 90,
      recycledContent: 25,
    },
    certificationDetails: [
      { name: 'ENERGY STAR', issuedDate: '2023-07-01', documentUrl: '#' },
      { name: 'LEED Credit Compliant', issuedDate: '2023-07-05', documentUrl: '#' },
      { name: 'EPD Verified', issuedDate: '2023-07-10', documentUrl: '#' },
    ],
    suppliers: [],
    priceRange: "$80 - $100 / sq ft",
    priceRangeMin: 80,
    priceRangeMax: 100,
    createdAt: '2023-05-20T00:00:00Z',
    updatedAt: '2024-05-20T00:00:00Z',
  },
  {
    id: "mat-007",
    name: "HempCrete Building Blocks",
    category: "Masonry",
    subcategory: "Bio-Based",
    manufacturer: "HempBuild Co.",
    image: "/placeholder-material.png",
    sustainabilityScore: 98,
    certifications: ["declare", "cradle-to-cradle", "epd"],
    leedPoints: 12,
    carbonFootprint: -5.2,
    recycledContent: 0,
    verifiedSuppliers: 2,
    shadowSuppliers: 6,
    featured: true,
    description: "Carbon-negative masonry units made from hemp hurds and lime binder. Breathable and insulating.",
    specifications: {
      "R-Value": "R-2.5 per inch",
      "Compressive Strength": "150 psi",
      "Density": "20 lbs/ft³",
      "Fire Rating": "Class A",
    },
    environmentalData: {
      gwp: -5.2,
      embodiedCarbon: -10,
      recyclableContent: 100,
      recycledContent: 0,
      voc: 0,
    },
    certificationDetails: [
      { name: 'Declare Label', issuedDate: '2023-08-15', documentUrl: '#' },
      { name: 'Cradle to Cradle Gold', issuedDate: '2023-09-01', documentUrl: '#' },
      { name: 'EPD Verified', issuedDate: '2023-09-05', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's9', name: 'Hemp Materials', location: 'Asheville, NC', verified: true, rating: 5.0 },
    ],
    priceRange: "$15 - $20 / block",
    priceRangeMin: 15,
    priceRangeMax: 20,
    createdAt: '2023-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: "mat-008",
    name: "RecycleRoof Metal Panels",
    category: "Roofing",
    subcategory: "Metal",
    manufacturer: "RecycleRoof Industries",
    image: "/placeholder-material.png",
    sustainabilityScore: 82,
    certifications: ["leed", "epd"],
    leedPoints: 5,
    carbonFootprint: 22.8,
    recycledContent: 70,
    verifiedSuppliers: 7,
    shadowSuppliers: 9,
    description: "Aluminum roofing panels made from 70% recycled post-consumer content. 100% recyclable at end of life.",
    specifications: {
      "Material": "Aluminum",
      "Thickness": "0.032 inch",
      "Finish": "Kynar 500",
      "Solar Reflectance": "> 0.70",
    },
    environmentalData: {
      gwp: 22.8,
      embodiedCarbon: 80,
      recyclableContent: 100,
      recycledContent: 70,
    },
    certificationDetails: [
      { name: 'LEED Credit Compliant', issuedDate: '2023-02-28', documentUrl: '#' },
      { name: 'EPD Verified', issuedDate: '2023-03-15', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's10', name: 'Metal Roof Outlet', location: 'Dallas, TX', verified: true, rating: 4.3 },
    ],
    priceRange: "$4 - $6 / sq ft",
    priceRangeMin: 4,
    priceRangeMax: 6,
    createdAt: '2023-07-10T00:00:00Z',
    updatedAt: '2024-07-10T00:00:00Z',
  },
  {
    id: "mat-009",
    name: "AquaGuard Permeable Pavers",
    category: "Hardscape",
    subcategory: "Pavers",
    manufacturer: "AquaGuard Outdoor",
    image: "/placeholder-material.png",
    sustainabilityScore: 76,
    certifications: ["leed", "breeam"],
    leedPoints: 4,
    carbonFootprint: 15.3,
    recycledContent: 40,
    verifiedSuppliers: 5,
    shadowSuppliers: 11,
    description: "Permeable concrete pavers designed to reduce stormwater runoff. Includes recycled aggregate.",
    specifications: {
      "Infiltration Rate": "> 100 inches/hour",
      "Compressive Strength": "5000 psi",
      "Dimensions": "4x8, 8x8",
      "Absorption": "< 5%",
    },
    environmentalData: {
      gwp: 15.3,
      embodiedCarbon: 25,
      recyclableContent: 100,
      recycledContent: 40,
    },
    certificationDetails: [
      { name: 'LEED Credit Compliant', issuedDate: '2023-04-20', documentUrl: '#' },
      { name: 'BREEAM Certified', issuedDate: '2023-05-10', documentUrl: '#' },
    ],
    suppliers: [],
    priceRange: "$5 - $8 / sq ft",
    priceRangeMin: 5,
    priceRangeMax: 8,
    createdAt: '2023-08-05T00:00:00Z',
    updatedAt: '2024-08-05T00:00:00Z',
  },
  {
    id: "mat-010",
    name: "EcoWall Bamboo Panels",
    category: "Wall Finishes",
    subcategory: "Wood Panels",
    manufacturer: "EcoWall Designs",
    image: "/placeholder-material.png",
    sustainabilityScore: 89,
    certifications: ["fsc", "greenguard", "leed"],
    leedPoints: 7,
    carbonFootprint: 8.7,
    recycledContent: 10,
    verifiedSuppliers: 4,
    shadowSuppliers: 6,
    description: "Rapidly renewable bamboo wall paneling. Formaldehyde-free adhesive.",
    specifications: {
      "Thickness": "1/2 inch",
      "Finish": "Matte Lacquer",
      "Fire Rating": "Class B",
      "Hardness": "1400 lbf (Janka)",
    },
    environmentalData: {
      gwp: 8.7,
      embodiedCarbon: 5,
      recyclableContent: 100,
      recycledContent: 10,
      voc: 0.01,
    },
    certificationDetails: [
      { name: 'FSC Certified', issuedDate: '2023-01-10', documentUrl: '#' },
      { name: 'GREENGUARD Gold', issuedDate: '2023-01-15', documentUrl: '#' },
      { name: 'LEED Credit Compliant', issuedDate: '2023-02-01', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's11', name: 'Bamboo Supply', location: 'Los Angeles, CA', verified: true, rating: 4.8 },
    ],
    priceRange: "$6 - $9 / sq ft",
    priceRangeMin: 6,
    priceRangeMax: 9,
    createdAt: '2023-09-01T00:00:00Z',
    updatedAt: '2024-09-01T00:00:00Z',
  },
  {
    id: "mat-011",
    name: "ZeroVOC Interior Paint",
    category: "Coatings",
    subcategory: "Paint",
    manufacturer: "PureCoat Labs",
    image: "/placeholder-material.png",
    sustainabilityScore: 94,
    certifications: ["greenguard", "declare", "leed"],
    leedPoints: 8,
    carbonFootprint: 2.1,
    recycledContent: 5,
    verifiedSuppliers: 9,
    shadowSuppliers: 14,
    description: "High-performance zero VOC interior latex paint. Safe for occupied spaces.",
    specifications: {
      "VOC Content": "< 5 g/L",
      "Volume Solids": "40%",
      "Coverage": "400 sq ft/gal",
      "Dry Time": "1 hour touch",
    },
    environmentalData: {
      gwp: 2.1,
      embodiedCarbon: 1.2,
      recyclableContent: 0,
      recycledContent: 5,
      voc: 0,
    },
    certificationDetails: [
      { name: 'GREENGUARD Gold', issuedDate: '2023-03-01', documentUrl: '#' },
      { name: 'Declare Label', issuedDate: '2023-03-05', documentUrl: '#' },
      { name: 'LEED Credit Compliant', issuedDate: '2023-03-10', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's12', name: 'Green Paints', location: 'Austin, TX', verified: true, rating: 4.7 },
    ],
    priceRange: "$45 - $60 / gallon",
    priceRangeMin: 45,
    priceRangeMax: 60,
    createdAt: '2023-10-01T00:00:00Z',
    updatedAt: '2024-10-01T00:00:00Z',
  },
  {
    id: "mat-012",
    name: "CorkTech Acoustic Flooring",
    category: "Flooring",
    subcategory: "Cork",
    manufacturer: "CorkTech International",
    image: "/placeholder-material.png",
    sustainabilityScore: 91,
    certifications: ["fsc", "epd", "cradle-to-cradle"],
    leedPoints: 9,
    carbonFootprint: 6.4,
    recycledContent: 65,
    verifiedSuppliers: 3,
    shadowSuppliers: 5,
    description: "Natural cork flooring with excellent acoustic properties and walking comfort.",
    specifications: {
      "Thickness": "10mm",
      "Density": "30 lbs/ft³",
      "Impact Sound Reduction": "18 dB",
      "Thermal Resistance": "R-0.8",
    },
    environmentalData: {
      gwp: 6.4,
      embodiedCarbon: 2,
      recyclableContent: 100,
      recycledContent: 65,
    },
    certificationDetails: [
      { name: 'FSC Certified', issuedDate: '2023-05-20', documentUrl: '#' },
      { name: 'EPD Verified', issuedDate: '2023-06-01', documentUrl: '#' },
      { name: 'Cradle to Cradle Silver', issuedDate: '2023-06-15', documentUrl: '#' },
    ],
    suppliers: [
      { id: 's13', name: 'Cork World', location: 'Portland, ME', verified: true, rating: 4.5 },
    ],
    priceRange: "$5 - $8 / sq ft",
    priceRangeMin: 5,
    priceRangeMax: 8,
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
];

export function getMaterial(id: string): MaterialDetail | undefined {
  return MOCK_MATERIALS.find((m) => m.id === id);
}
