// frontend/src/pages/BuyerDashboard/ProjectDetail.tsx
import React, { useState, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useProjects } from '../../context/ProjectContext';
import { MOCK_PRODUCTS, Product } from '../../mocks/productData';
import ProductCard from '../../components/ProductCard'; // Reusing for now, will adapt as needed
import AddProductsModal from '../../components/Projects/AddProductsModal';

const ProjectDetail: React.FC = () => {
  const { projectId } = useParams<{ projectId: string }>();
  const { projects, updateProject, removeProductFromProject } = useProjects();
  const navigate = useNavigate();

  const project = useMemo(() => projects.find(p => p.id === Number(projectId)), [projects, projectId]);
  const projectProducts = useMemo(() => MOCK_PRODUCTS.filter(p => project?.productIds.includes(p.id)), [project]);

  const [isEditingName, setIsEditingName] = useState(false);
  const [projectName, setProjectName] = useState(project?.name || '');
  const [isAddProductsModalOpen, setIsAddProductsModalOpen] = useState(false);

  const totalCarbonFootprint = useMemo(() => {
    return Math.round(projectProducts.reduce((sum, p) => sum + (p.epd?.gwp || 0), 0));
  }, [projectProducts]);

  const totalEstimatedCost = useMemo(() => {
    return projectProducts.reduce((sum, p) => sum + (p.price || 0), 0);
  }, [projectProducts]);

  if (!project) {
    return (
      <div className="p-8 text-center">
        <h1 className="text-2xl font-bold">Project not found</h1>
        <button onClick={() => navigate('/dashboard/buyer/projects')} className="mt-4 px-6 py-2 bg-primary text-white rounded-lg">
          Back to Projects
        </button>
      </div>
    );
  }

  const handleNameUpdate = () => {
    if (projectName.trim()) {
      updateProject(project.id, { name: projectName });
      setIsEditingName(false);
    }
  };

  const exportProject = () => {
    const reportParts = [
      `PROJECT REPORT`,
      `=============`,
      `\nProject: ${project.name}`,
      `Type: ${project.type}`,
      `LEED Target: ${project.targetLEED}`,
      `Created: ${new Date(project.createdAt).toLocaleDateString()}`,
      `\nPRODUCTS (${projectProducts.length})`,
      `------------`,
      ...projectProducts.map(p =>
        `\n${p.name}\n` +
        `   - Supplier: ${p.supplier}\n` +
        `   - Recycled Content: ${p.recycledContent}%\n` +
        `   - Carbon Footprint: ${p.epd.gwp} kg CO2e\n` +
        `   - Certifications: ${p.certifications.join(', ')}\n` +
        `   - Cost: $${p.price?.toLocaleString() || 'N/A'}`
      ),
      `\nSUMMARY`,
      `-------`,
      `Total Products: ${projectProducts.length}`,
      `Total Carbon Footprint: ${totalCarbonFootprint.toLocaleString()} kg CO2e`,
      `Total Estimated Cost: $${totalEstimatedCost.toLocaleString()}`,
      `\n---\nGenerated by GreenChainz\ngreenchainz.com`
    ];

    const blob = new Blob([reportParts.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.name.replace(/\s+/g, '-')}-report.txt`;
    a.click();
    URL.revokeObjectURL(url);
    alert('Project report exported!');
  };

  return (
    <div className="p-4 sm:p-8">
      {/* Header */}
      <div className="flex flex-wrap justify-between items-center mb-8 gap-4">
        <div>
          {isEditingName ? (
            <input
              type="text"
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
              onBlur={handleNameUpdate}
              onKeyPress={(e) => e.key === 'Enter' && handleNameUpdate()}
              className="text-3xl font-bold border-b-2 border-primary"
              autoFocus
            />
          ) : (
            <h1 onClick={() => setIsEditingName(true)} className="text-3xl font-bold cursor-pointer">{project.name}</h1>
          )}
          <p className="text-gray-600 mt-1">{project.description}</p>
        </div>
        <div className="flex items-center space-x-2">
          <button onClick={() => setIsAddProductsModalOpen(true)} className="px-4 py-2 bg-primary text-white font-semibold rounded-lg">Add Products</button>
          <button onClick={exportProject} className="px-4 py-2 border border-gray-300 rounded-lg">Export Project</button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        <div className="bg-white p-6 rounded-lg border">
          <h3 className="text-lg font-medium text-gray-700">Total Carbon Footprint</h3>
          <p className="text-3xl font-bold mt-2">{totalCarbonFootprint.toLocaleString()} kg CO2e</p>
        </div>
        <div className="bg-white p-6 rounded-lg border">
          <h3 className="text-lg font-medium text-gray-700">Total Estimated Cost</h3>
          <p className="text-3xl font-bold mt-2">${totalEstimatedCost.toLocaleString()}</p>
        </div>
      </div>

      {/* Product List */}
      <h2 className="text-2xl font-bold mb-6">Products in Project</h2>
      {projectProducts.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {projectProducts.map(product => (
            <div key={product.id} className="relative">
              <ProductCard product={product} />
              <button
                onClick={() => removeProductFromProject(project.id, product.id)}
                className="absolute top-2 right-2 bg-red-500 text-white rounded-full p-2 text-xs"
                aria-label="Remove from project"
              >
                X
              </button>
            </div>
          ))}
        </div>
      ) : (
        <div className="text-center py-16 border-2 border-dashed rounded-lg">
          <h3 className="text-xl">No products in this project yet.</h3>
          <button onClick={() => setIsAddProductsModalOpen(true)} className="mt-4 px-6 py-2 bg-primary text-white rounded-lg">
            Add Products
          </button>
        </div>
      )}

      {isAddProductsModalOpen && (
        <AddProductsModal
          projectId={project.id}
          onClose={() => setIsAddProductsModalOpen(false)}
        />
      )}
    </div>
  );
};

export default ProjectDetail;
