AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 buckets for GreenChainz platform - product images, EPD documents, and backups'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
    Description: Deployment environment

  CloudFrontDomain:
    Type: String
    Default: cdn.greenchainz.com
    Description: CloudFront domain for product images CDN

  ReplicationRegion:
    Type: String
    Default: us-west-2
    Description: Cross-region replication destination for backups

Resources:
  # ============================================
  # Product Images Bucket (Public via CloudFront)
  # ============================================
  ProductImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gc-product-images-prod
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
            AllowedOrigins:
              - 'https://greenchainz.com'
              - 'https://www.greenchainz.com'
              - 'https://*.vercel.app'
            MaxAge: 3600
            ExposedHeaders:
              - ETag
              - x-amz-meta-custom-header
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90
            NoncurrentVersionExpiration:
              NoncurrentDays: 365
      Tags:
        - Key: project
          Value: greenchainz
        - Key: environment
          Value: !Ref Environment
        - Key: purpose
          Value: product-images

  # Origin Access Identity for CloudFront
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for GreenChainz product images

  # Bucket Policy for CloudFront access
  ProductImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProductImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}'
            Action: s3:GetObject
            Resource: !Sub '${ProductImagesBucket.Arn}/*'

  # ============================================
  # EPD Documents Bucket (Private, Signed URLs)
  # ============================================
  EPDDocumentsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: gc-epd-documents-prod
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: RetainAllVersions7Years
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 2555
      ObjectLockEnabled: false
      Tags:
        - Key: project
          Value: greenchainz
        - Key: environment
          Value: !Ref Environment
        - Key: purpose
          Value: epd-documents
        - Key: compliance
          Value: 7-year-retention

  # ============================================
  # Data Backups Bucket (Private, Cross-Region Replication)
  # ============================================
  DataBackupsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gc-data-backups-prod
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToGlacierAndDelete
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
            Expiration:
              Days: 365
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Id: CrossRegionReplication
            Status: Enabled
            Priority: 1
            DeleteMarkerReplication:
              Status: Disabled
            Filter:
              Prefix: ''
            Destination:
              Bucket: !Sub 'arn:aws:s3:::gc-data-backups-replica-${ReplicationRegion}'
              StorageClass: STANDARD_IA
      Tags:
        - Key: project
          Value: greenchainz
        - Key: environment
          Value: !Ref Environment
        - Key: purpose
          Value: database-backups

  # Replication Role for cross-region backup
  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: gc-s3-replication-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource: !GetAtt DataBackupsBucket.Arn
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource: !Sub '${DataBackupsBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: !Sub 'arn:aws:s3:::gc-data-backups-replica-${ReplicationRegion}/*'
      Tags:
        - Key: project
          Value: greenchainz
        - Key: environment
          Value: !Ref Environment

  # ============================================
  # IAM User for Lambda/Backend Access
  # ============================================
  S3AccessUser:
    Type: AWS::IAM::User
    Properties:
      UserName: greenchainz-s3-service
      Tags:
        - Key: project
          Value: greenchainz
        - Key: environment
          Value: !Ref Environment

  S3AccessUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3AccessUser

  S3AccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GreenChainzS3AccessPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:PutObjectAcl
            Resource:
              - !Sub '${ProductImagesBucket.Arn}/*'
              - !Sub '${EPDDocumentsBucket.Arn}/*'
              - !Sub '${DataBackupsBucket.Arn}/*'
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - !GetAtt ProductImagesBucket.Arn
              - !GetAtt EPDDocumentsBucket.Arn
              - !GetAtt DataBackupsBucket.Arn
      Users:
        - !Ref S3AccessUser

Outputs:
  ProductImagesBucketName:
    Description: Name of the product images bucket
    Value: !Ref ProductImagesBucket
    Export:
      Name: !Sub '${AWS::StackName}-ProductImagesBucket'

  ProductImagesBucketArn:
    Description: ARN of the product images bucket
    Value: !GetAtt ProductImagesBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProductImagesBucketArn'

  EPDDocumentsBucketName:
    Description: Name of the EPD documents bucket
    Value: !Ref EPDDocumentsBucket
    Export:
      Name: !Sub '${AWS::StackName}-EPDDocumentsBucket'

  EPDDocumentsBucketArn:
    Description: ARN of the EPD documents bucket
    Value: !GetAtt EPDDocumentsBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EPDDocumentsBucketArn'

  DataBackupsBucketName:
    Description: Name of the data backups bucket
    Value: !Ref DataBackupsBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBackupsBucket'

  DataBackupsBucketArn:
    Description: ARN of the data backups bucket
    Value: !GetAtt DataBackupsBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DataBackupsBucketArn'

  CloudFrontOriginAccessIdentityId:
    Description: CloudFront Origin Access Identity ID
    Value: !Ref CloudFrontOriginAccessIdentity
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontOAI'

  S3AccessKeyId:
    Description: Access Key ID for S3 service user
    Value: !Ref S3AccessUserAccessKey

  S3SecretAccessKey:
    Description: Secret Access Key for S3 service user (store securely)
    Value: !GetAtt S3AccessUserAccessKey.SecretAccessKey
