-- ============================================
-- REVIT INTEGRATION SCHEMA
-- ============================================
-- Tables to support the Revit add-in connector from external repo
-- Auth: Azure Entra ID only
-- Version: 1.0.0

-- Revit Plugin Registrations
-- Tracks registered Revit add-in instances (per organization/user)
CREATE TABLE IF NOT EXISTS Revit_Plugin_Registrations (
  RegistrationID BIGSERIAL PRIMARY KEY,
  UserID BIGINT REFERENCES Users(UserID) ON DELETE CASCADE,
  AzureEntraObjectID VARCHAR(255) NOT NULL,  -- Azure Entra ID object ID (oid claim)
  AzureEntraTenantID VARCHAR(255) NOT NULL,  -- Azure tenant ID
  PluginInstanceID VARCHAR(255) UNIQUE NOT NULL,  -- Unique ID generated by plugin on install
  RevitVersion VARCHAR(50),  -- e.g., "2024", "2025"
  PluginVersion VARCHAR(50),  -- e.g., "1.0.0"
  MachineName VARCHAR(255),  -- Computer name for licensing/audit
  IsActive BOOLEAN DEFAULT TRUE,
  LastHeartbeatAt TIMESTAMP,
  ActivatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DeactivatedAt TIMESTAMP,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_entra_plugin UNIQUE (AzureEntraObjectID, PluginInstanceID)
);

-- Revit Sessions
-- Tracks active Revit sessions for real-time sync
CREATE TABLE IF NOT EXISTS Revit_Sessions (
  SessionID BIGSERIAL PRIMARY KEY,
  RegistrationID BIGINT REFERENCES Revit_Plugin_Registrations(RegistrationID) ON DELETE CASCADE,
  UserID BIGINT REFERENCES Users(UserID) ON DELETE CASCADE,
  ProjectFileHash VARCHAR(64),  -- SHA256 of .rvt file for identifying projects
  ProjectName VARCHAR(500),
  ProjectPath TEXT,  -- Local path in Revit
  SessionToken VARCHAR(255) UNIQUE NOT NULL,  -- Short-lived session token
  StartedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LastActivityAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EndedAt TIMESTAMP,
  Status VARCHAR(50) DEFAULT 'active' CHECK (Status IN ('active', 'paused', 'ended', 'expired')),
  Metadata JSONB DEFAULT '{}'::jsonb  -- Flexible metadata
);

-- Revit Projects
-- Master list of Revit projects synced to GreenChainz
CREATE TABLE IF NOT EXISTS Revit_Projects (
  ProjectID BIGSERIAL PRIMARY KEY,
  UserID BIGINT REFERENCES Users(UserID) ON DELETE SET NULL,
  ProjectFileHash VARCHAR(64) UNIQUE,  -- SHA256 of .rvt file
  ProjectName VARCHAR(500) NOT NULL,
  ProjectNumber VARCHAR(100),  -- Revit project number field
  ClientName VARCHAR(255),
  Location VARCHAR(500),
  BuildingType VARCHAR(100),  -- Commercial, Residential, etc.
  GrossArea DECIMAL(15, 2),  -- Square feet/meters
  AreaUnit VARCHAR(20) DEFAULT 'sqft',
  TargetCertification VARCHAR(100),  -- "LEED Gold", "BREEAM Excellent", etc.
  SustainabilityScore INTEGER CHECK (SustainabilityScore >= 0 AND SustainabilityScore <= 100),
  LastSyncedAt TIMESTAMP,
  SyncStatus VARCHAR(50) DEFAULT 'pending' CHECK (SyncStatus IN ('pending', 'syncing', 'synced', 'error')),
  SyncErrorMessage TEXT,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Revit Material Mappings
-- Maps Revit materials to GreenChainz products/sustainability data
CREATE TABLE IF NOT EXISTS Revit_Material_Mappings (
  MappingID BIGSERIAL PRIMARY KEY,
  ProjectID BIGINT REFERENCES Revit_Projects(ProjectID) ON DELETE CASCADE,
  RevitMaterialID VARCHAR(255) NOT NULL,  -- Revit's internal material ID
  RevitMaterialName VARCHAR(500) NOT NULL,
  RevitMaterialCategory VARCHAR(255),  -- Revit category
  
  -- GreenChainz mapping
  GCProductID BIGINT REFERENCES Products(ProductID) ON DELETE SET NULL,
  GCCategoryID BIGINT REFERENCES Product_Categories(CategoryID) ON DELETE SET NULL,
  
  -- Sustainability data (cached from product or manual entry)
  EmbodiedCarbonKgCO2e DECIMAL(15, 4),
  EPDNumber VARCHAR(255),
  FSCCertified BOOLEAN DEFAULT FALSE,
  LEEDPoints DECIMAL(5, 2),
  
  -- Quantity data from Revit
  TotalArea DECIMAL(15, 4),
  TotalVolume DECIMAL(15, 4),
  TotalCount INTEGER,
  QuantityUnit VARCHAR(50),
  
  -- Mapping status
  MappingStatus VARCHAR(50) DEFAULT 'unmapped' CHECK (MappingStatus IN ('unmapped', 'auto_mapped', 'manual_mapped', 'verified', 'rejected')),
  ConfidenceScore DECIMAL(5, 4),  -- 0.0000 to 1.0000 for auto-mapping confidence
  MappedByUserID BIGINT REFERENCES Users(UserID) ON DELETE SET NULL,
  MappedAt TIMESTAMP,
  
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_project_material UNIQUE (ProjectID, RevitMaterialID)
);

-- Revit Sync Events
-- Immutable log of all sync operations (event sourcing)
CREATE TABLE IF NOT EXISTS Revit_Sync_Events (
  EventID BIGSERIAL PRIMARY KEY,
  SessionID BIGINT REFERENCES Revit_Sessions(SessionID) ON DELETE SET NULL,
  ProjectID BIGINT REFERENCES Revit_Projects(ProjectID) ON DELETE SET NULL,
  UserID BIGINT REFERENCES Users(UserID) ON DELETE SET NULL,
  EventType VARCHAR(100) NOT NULL CHECK (EventType IN (
    'SESSION_START', 'SESSION_END', 'SESSION_HEARTBEAT',
    'PROJECT_SYNC_START', 'PROJECT_SYNC_COMPLETE', 'PROJECT_SYNC_ERROR',
    'MATERIAL_EXTRACTED', 'MATERIAL_MAPPED', 'MATERIAL_UPDATED',
    'SCORE_CALCULATED', 'RFQ_INITIATED', 'EXPORT_GENERATED'
  )),
  EventData JSONB NOT NULL DEFAULT '{}'::jsonb,
  IPAddress VARCHAR(45),
  UserAgent TEXT,
  Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Revit Sustainability Snapshots
-- Point-in-time sustainability scores for projects
CREATE TABLE IF NOT EXISTS Revit_Sustainability_Snapshots (
  SnapshotID BIGSERIAL PRIMARY KEY,
  ProjectID BIGINT REFERENCES Revit_Projects(ProjectID) ON DELETE CASCADE,
  SessionID BIGINT REFERENCES Revit_Sessions(SessionID) ON DELETE SET NULL,
  
  -- Overall scores
  OverallScore INTEGER CHECK (OverallScore >= 0 AND OverallScore <= 100),
  LEEDPointsTotal DECIMAL(5, 2),
  LEEDPointsPossible DECIMAL(5, 2),
  
  -- Environmental metrics
  TotalEmbodiedCarbonKg DECIMAL(15, 4),
  CarbonPerSqft DECIMAL(10, 4),
  
  -- Material coverage
  TotalMaterialsCount INTEGER,
  MappedMaterialsCount INTEGER,
  VerifiedMaterialsCount INTEGER,
  FSCMaterialsPercentage DECIMAL(5, 2),
  EPDCoveragePercentage DECIMAL(5, 2),
  
  -- Breakdown by category
  CategoryBreakdown JSONB DEFAULT '[]'::jsonb,
  
  -- Recommendations
  Recommendations JSONB DEFAULT '[]'::jsonb,
  
  SnapshotReason VARCHAR(100),  -- 'manual', 'auto_sync', 'export'
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Revit API Tokens
-- Short-lived tokens for Revit plugin authentication (supplement to Azure Entra ID)
CREATE TABLE IF NOT EXISTS Revit_API_Tokens (
  TokenID BIGSERIAL PRIMARY KEY,
  UserID BIGINT REFERENCES Users(UserID) ON DELETE CASCADE,
  RegistrationID BIGINT REFERENCES Revit_Plugin_Registrations(RegistrationID) ON DELETE CASCADE,
  TokenHash VARCHAR(64) NOT NULL,  -- SHA256 of token (never store plaintext)
  Scopes VARCHAR(500) DEFAULT 'read,write',  -- Comma-separated scopes
  ExpiresAt TIMESTAMP NOT NULL,
  RevokedAt TIMESTAMP,
  IssuedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LastUsedAt TIMESTAMP,
  CONSTRAINT unique_token_hash UNIQUE (TokenHash)
);

-- ============================================
-- INDEXES
-- ============================================

-- Plugin registrations
CREATE INDEX IF NOT EXISTS idx_revit_reg_user ON Revit_Plugin_Registrations(UserID);
CREATE INDEX IF NOT EXISTS idx_revit_reg_entra ON Revit_Plugin_Registrations(AzureEntraObjectID);
CREATE INDEX IF NOT EXISTS idx_revit_reg_active ON Revit_Plugin_Registrations(IsActive) WHERE IsActive = TRUE;

-- Sessions
CREATE INDEX IF NOT EXISTS idx_revit_sessions_reg ON Revit_Sessions(RegistrationID);
CREATE INDEX IF NOT EXISTS idx_revit_sessions_user ON Revit_Sessions(UserID);
CREATE INDEX IF NOT EXISTS idx_revit_sessions_active ON Revit_Sessions(Status, LastActivityAt) WHERE Status = 'active';
CREATE INDEX IF NOT EXISTS idx_revit_sessions_token ON Revit_Sessions(SessionToken);

-- Projects
CREATE INDEX IF NOT EXISTS idx_revit_projects_user ON Revit_Projects(UserID);
CREATE INDEX IF NOT EXISTS idx_revit_projects_hash ON Revit_Projects(ProjectFileHash);
CREATE INDEX IF NOT EXISTS idx_revit_projects_sync ON Revit_Projects(SyncStatus, LastSyncedAt);

-- Material mappings
CREATE INDEX IF NOT EXISTS idx_revit_materials_project ON Revit_Material_Mappings(ProjectID);
CREATE INDEX IF NOT EXISTS idx_revit_materials_product ON Revit_Material_Mappings(GCProductID);
CREATE INDEX IF NOT EXISTS idx_revit_materials_status ON Revit_Material_Mappings(MappingStatus);

-- Sync events
CREATE INDEX IF NOT EXISTS idx_revit_events_session ON Revit_Sync_Events(SessionID, Timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_revit_events_project ON Revit_Sync_Events(ProjectID, Timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_revit_events_user ON Revit_Sync_Events(UserID, Timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_revit_events_type ON Revit_Sync_Events(EventType, Timestamp DESC);

-- Snapshots
CREATE INDEX IF NOT EXISTS idx_revit_snapshots_project ON Revit_Sustainability_Snapshots(ProjectID, CreatedAt DESC);

-- API Tokens
CREATE INDEX IF NOT EXISTS idx_revit_tokens_user ON Revit_API_Tokens(UserID);
CREATE INDEX IF NOT EXISTS idx_revit_tokens_reg ON Revit_API_Tokens(RegistrationID);
CREATE INDEX IF NOT EXISTS idx_revit_tokens_valid ON Revit_API_Tokens(ExpiresAt) WHERE RevokedAt IS NULL;

-- ============================================
-- FUNCTIONS
-- ============================================

-- Function to clean up expired sessions (run periodically)
CREATE OR REPLACE FUNCTION cleanup_expired_revit_sessions()
RETURNS INTEGER AS $$
DECLARE
  expired_count INTEGER;
BEGIN
  UPDATE Revit_Sessions
  SET Status = 'expired', EndedAt = CURRENT_TIMESTAMP
  WHERE Status = 'active' 
    AND LastActivityAt < CURRENT_TIMESTAMP - INTERVAL '2 hours';
  
  GET DIAGNOSTICS expired_count = ROW_COUNT;
  RETURN expired_count;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate project sustainability score
CREATE OR REPLACE FUNCTION calculate_revit_project_score(p_project_id BIGINT)
RETURNS INTEGER AS $$
DECLARE
  score INTEGER;
  total_materials INTEGER;
  mapped_materials INTEGER;
  verified_materials INTEGER;
  fsc_count INTEGER;
  epd_count INTEGER;
BEGIN
  SELECT 
    COUNT(*),
    COUNT(*) FILTER (WHERE MappingStatus IN ('auto_mapped', 'manual_mapped', 'verified')),
    COUNT(*) FILTER (WHERE MappingStatus = 'verified'),
    COUNT(*) FILTER (WHERE FSCCertified = TRUE),
    COUNT(*) FILTER (WHERE EPDNumber IS NOT NULL)
  INTO total_materials, mapped_materials, verified_materials, fsc_count, epd_count
  FROM Revit_Material_Mappings
  WHERE ProjectID = p_project_id;
  
  IF total_materials = 0 THEN
    RETURN 0;
  END IF;
  
  -- Score formula: 40% mapping coverage + 30% verification + 15% FSC + 15% EPD
  score := (
    (40 * mapped_materials / total_materials) +
    (30 * verified_materials / total_materials) +
    (15 * fsc_count / total_materials) +
    (15 * epd_count / total_materials)
  )::INTEGER;
  
  RETURN LEAST(score, 100);
END;
$$ LANGUAGE plpgsql;
