export const mockMaterials = [
  'Acoustic insulation',
  'Fiberglass insulation',
  'Mineral wool insulation',
  'Cellulose insulation',
  'Polystyrene insulation',
  'Spray foam insulation',
  'Structural insulated panels (SIPs)',
  'Insulated concrete forms (ICFs)',
  'Bamboo flooring',
  'Cork flooring',
  'Reclaimed wood flooring',
  'Linoleum flooring',
  'Rubber flooring',
  'Clay bricks',
  'Concrete masonry units (CMUs)',
  'Autoclaved aerated concrete (AAC)',
  'Cross-laminated timber (CLT)',
  'Glulam beams',
  'Steel framing',
  'Green roof systems',
  'Cool roof coatings',
  'Solar shingles',
  'Clay roof tiles',
  'Metal roofing',
];
